### ISSUE TITLE
vue-cli3-dome  多项目模块打包

### ISSUE THREAD

**Issue by ZKaiCode** [Hanpeng-Chen/hampton-demo-repo#15]
这个项目下载下来运行后 执行npm run serve 运行起来 啥都没有 没法正常显示组件 打包后访问也是空页   我看这边每个页面配置的About组件  都有内容

**Comment by Hanpeng-Chen** [comment]
@ZKaiCode 不同module路径：http://localhost:8080/projectA/#/​     
http://localhost:8080/projectB/#/
