### ISSUE TITLE
打包之后部署到测试服务器，页面空白

### ISSUE THREAD

**Issue by xy0514** [Hanpeng-Chen/hampton-demo-repo#17]

**Comment by Hanpeng-Chen** [comment]
在vue.config.js中要配置publicpath，例如
`publicPath: projectname ? '/' + projectname : '/',`

**Comment by xy0514** [comment]
配置了也不行
![X {1}_D XW6{)YBH(})Y%)2](https://user-images.githubusercontent.com/48755622/78203440-8c574700-74c9-11ea-8c15-785199a78534.png)

**Comment by xy0514** [comment]
现在页面可以访问，凡是路由失效了，使用的是history模式
