### ISSUE TITLE
这样情况好像不支持？一次执行build，将多个不同的项目的文件各自编译打包，生成不同的文件目录

### ISSUE THREAD

**Issue by 949942167** [Hanpeng-Chen/hampton-demo-repo#3]

**Comment by Hanpeng-Chen** [comment]
@949942167 写个node.js脚本可以编译打包所有模块
脚本参考下面代码
`
var glob = require('glob')
const { spawnSync } = require('child_process')
var env = process.argv[2] || 'test'

var items = glob.sync( './src/modules/*/main.js')
var cmd = ''
items.forEach((filepath, i) => {
  var fileList = filepath.split('/')
  var fileName = fileList[fileList.length-2]
  var tmp = 'npm run build'
  if (env === 'prod') {
    // 生产环境
    cmd += tmp + ':prod ' + fileName
  } else if (env ==='test') {
    cmd += tmp + ' ' + fileName
  }
  if (i !== (items.length - 1)) {
    cmd += ' & '
  }
})
cmd = cmd.substr(0, cmd.length)
spawnSync(cmd, [], {shell: true, detached: true})
console.log('==============================打包完成==========================================')
`

js放在根目录下，执行`node build-all.js`，如果是打生产包，后面加上prod

**Comment by 949942167** [comment]
可以的，十分感谢
