### ISSUE TITLE
打包后页面出不来

### ISSUE THREAD

**Issue by yujianhui1993** [Hanpeng-Chen/hampton-demo-repo#4]
执行 npm run build projectA后
并将生成的dist 下的 projectA 放在服务器上，但是访问却是空白页面，连资源文件都没有取到，请问是什么问题赵成的呢。 @HamptonChen

**Comment by Hanpeng-Chen** [comment]
> 执行 npm run build projectA后
> 并将生成的dist 下的 projectA 放在服务器上，但是访问却是空白页面，连资源文件都没有取到，请问是什么问题赵成的呢。 @HamptonChen

![image](https://user-images.githubusercontent.com/20657777/66975967-bd39f000-f0d2-11e9-9111-766f95f13d41.png)
![image](https://user-images.githubusercontent.com/20657777/66975996-d93d9180-f0d2-11e9-92a6-f1dde6fce601.png)
你看下是不是publicPath配置有问题 @yujianhui1993

**Comment by yujianhui1993** [comment]
是的 publicPath 需要配置 
publicPath: process.env.NODE_ENV == 'production'?`/${projectname}/`:'/',

![image](https://user-images.githubusercontent.com/7228360/67004383-c8147500-f112-11e9-934a-b0bd2d05e672.png)
还修改一处这个

**Comment by githubsmoker** [comment]
按照你的这个配置 但是打包出来还是空白什么情况呢

**Comment by yujianhui1993** [comment]
> 按照你的这个配置 但是打包出来还是空白什么情况呢

这是个什么项目，几年前了，不记得是什么功能了。

**Comment by githubsmoker** [comment]
就是几个子项目 然后配置打包路径 打包出来是空白 这个问题
